source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'ReactNativeAutoUpdater_Example', :exclusive => true do
  pod "ReactNativeAutoUpdater", :path => "../../"
end

target 'ReactNativeAutoUpdater_Tests', :exclusive => true do
  pod "ReactNativeAutoUpdater", :path => "../../"

  
end
